{
  "artifacts": [],
  "command": "train",
  "experiment": {
    "base_dir": "/Users/dustin/Desktop/Clubs/RAISE/tf2multiagentrl",
    "dependencies": [
      "numpy==1.18.5",
      "sacred==0.8.1",
      "tensorflow==2.3.1"
    ],
    "mainfile": "train.py",
    "name": "train",
    "repositories": [
      {
        "commit": "8b63174b5d314cbf29a7ff2414d5999a0224c03d",
        "dirty": true,
        "url": "https://github.com/JohannesAck/tf2multiagentrl.git"
      },
      {
        "commit": "8b63174b5d314cbf29a7ff2414d5999a0224c03d",
        "dirty": true,
        "url": "https://github.com/JohannesAck/tf2multiagentrl.git"
      },
      {
        "commit": "8b63174b5d314cbf29a7ff2414d5999a0224c03d",
        "dirty": true,
        "url": "https://github.com/JohannesAck/tf2multiagentrl.git"
      },
      {
        "commit": "8b63174b5d314cbf29a7ff2414d5999a0224c03d",
        "dirty": true,
        "url": "https://github.com/JohannesAck/tf2multiagentrl.git"
      },
      {
        "commit": "8b63174b5d314cbf29a7ff2414d5999a0224c03d",
        "dirty": true,
        "url": "https://github.com/JohannesAck/tf2multiagentrl.git"
      },
      {
        "commit": "8b63174b5d314cbf29a7ff2414d5999a0224c03d",
        "dirty": true,
        "url": "https://github.com/JohannesAck/tf2multiagentrl.git"
      },
      {
        "commit": "8b63174b5d314cbf29a7ff2414d5999a0224c03d",
        "dirty": true,
        "url": "https://github.com/JohannesAck/tf2multiagentrl.git"
      },
      {
        "commit": "8b63174b5d314cbf29a7ff2414d5999a0224c03d",
        "dirty": true,
        "url": "https://github.com/JohannesAck/tf2multiagentrl.git"
      },
      {
        "commit": "8b63174b5d314cbf29a7ff2414d5999a0224c03d",
        "dirty": true,
        "url": "https://github.com/JohannesAck/tf2multiagentrl.git"
      },
      {
        "commit": "8b63174b5d314cbf29a7ff2414d5999a0224c03d",
        "dirty": true,
        "url": "https://github.com/JohannesAck/tf2multiagentrl.git"
      },
      {
        "commit": "8b63174b5d314cbf29a7ff2414d5999a0224c03d",
        "dirty": true,
        "url": "https://github.com/JohannesAck/tf2multiagentrl.git"
      },
      {
        "commit": "8b63174b5d314cbf29a7ff2414d5999a0224c03d",
        "dirty": true,
        "url": "https://github.com/JohannesAck/tf2multiagentrl.git"
      },
      {
        "commit": "8b63174b5d314cbf29a7ff2414d5999a0224c03d",
        "dirty": true,
        "url": "https://github.com/JohannesAck/tf2multiagentrl.git"
      }
    ],
    "sources": [
      [
        "tf2marl/__init__.py",
        "_sources/__init___d41d8cd98f00b204e9800998ecf8427e.py"
      ],
      [
        "tf2marl/agents/AbstractAgent.py",
        "_sources/AbstractAgent_80c905362ae0eb744cb60a36b67e4284.py"
      ],
      [
        "tf2marl/agents/__init__.py",
        "_sources/__init___9a6daa8b314d3de07ce7c22c1c12d10c.py"
      ],
      [
        "tf2marl/agents/mad3pg.py",
        "_sources/mad3pg_67e18f39237730c3271ee9fb7b1c521f.py"
      ],
      [
        "tf2marl/agents/maddpg.py",
        "_sources/maddpg_653bd664142a9d9f93fb865fe8ac61d0.py"
      ],
      [
        "tf2marl/agents/masac.py",
        "_sources/masac_3f97fe6b8a42135ffb9f6a988a26087c.py"
      ],
      [
        "tf2marl/agents/matd3.py",
        "_sources/matd3_e1189e442ef8d7d325da452af12b14ba.py"
      ],
      [
        "tf2marl/common/__init__.py",
        "_sources/__init___d41d8cd98f00b204e9800998ecf8427e.py"
      ],
      [
        "tf2marl/common/logger.py",
        "_sources/logger_cd041bc34b49684cd6cccfb6a1011091.py"
      ],
      [
        "tf2marl/common/util.py",
        "_sources/util_7dc340240c565a480b325a60613a6c5d.py"
      ],
      [
        "tf2marl/multiagent/SG_environment.py",
        "_sources/SG_environment_ed17626d7176f4c318b9aca9d74ed4a2.py"
      ],
      [
        "tf2marl/multiagent/__init__.py",
        "_sources/__init___5bd42acbde1ad76ba49d7937cab56f12.py"
      ],
      [
        "train.py",
        "_sources/train_507efa83751f983f4295269fee3c9579.py"
      ]
    ]
  },
  "fail_trace": [
    "Traceback (most recent call last):\n",
    "  File \"/Users/dustin/Desktop/Clubs/RAISE/tf2multiagentrl/tf2marl/multiagent/utils.py\", line 31, in price_signal\n    df = pd.read_csv(csv_path)\n",
    "  File \"/Users/dustin/anaconda3/envs/RAISE/lib/python3.6/site-packages/pandas/io/parsers.py\", line 688, in read_csv\n    return _read(filepath_or_buffer, kwds)\n",
    "  File \"/Users/dustin/anaconda3/envs/RAISE/lib/python3.6/site-packages/pandas/io/parsers.py\", line 454, in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\n",
    "  File \"/Users/dustin/anaconda3/envs/RAISE/lib/python3.6/site-packages/pandas/io/parsers.py\", line 948, in __init__\n    self._make_engine(self.engine)\n",
    "  File \"/Users/dustin/anaconda3/envs/RAISE/lib/python3.6/site-packages/pandas/io/parsers.py\", line 1180, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n",
    "  File \"/Users/dustin/anaconda3/envs/RAISE/lib/python3.6/site-packages/pandas/io/parsers.py\", line 2010, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n",
    "  File \"pandas/_libs/parsers.pyx\", line 382, in pandas._libs.parsers.TextReader.__cinit__\n",
    "  File \"pandas/_libs/parsers.pyx\", line 674, in pandas._libs.parsers.TextReader._setup_parser_source\n",
    "FileNotFoundError: [Errno 2] No such file or directory: 'building_data.csv'\n",
    "\nDuring handling of the above exception, another exception occurred:\n\n",
    "Traceback (most recent call last):\n",
    "  File \"/Users/dustin/Desktop/Clubs/RAISE/tf2multiagentrl/tf2marl/multiagent/utils.py\", line 34, in price_signal\n    df = pd.read_csv(csv_path_2)\n",
    "  File \"/Users/dustin/anaconda3/envs/RAISE/lib/python3.6/site-packages/pandas/io/parsers.py\", line 688, in read_csv\n    return _read(filepath_or_buffer, kwds)\n",
    "  File \"/Users/dustin/anaconda3/envs/RAISE/lib/python3.6/site-packages/pandas/io/parsers.py\", line 454, in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\n",
    "  File \"/Users/dustin/anaconda3/envs/RAISE/lib/python3.6/site-packages/pandas/io/parsers.py\", line 948, in __init__\n    self._make_engine(self.engine)\n",
    "  File \"/Users/dustin/anaconda3/envs/RAISE/lib/python3.6/site-packages/pandas/io/parsers.py\", line 1180, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n",
    "  File \"/Users/dustin/anaconda3/envs/RAISE/lib/python3.6/site-packages/pandas/io/parsers.py\", line 2010, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n",
    "  File \"pandas/_libs/parsers.pyx\", line 382, in pandas._libs.parsers.TextReader.__cinit__\n",
    "  File \"pandas/_libs/parsers.pyx\", line 674, in pandas._libs.parsers.TextReader._setup_parser_source\n",
    "FileNotFoundError: [Errno 2] No such file or directory: '../gym-socialgame/gym_socialgame/envs/building_data.csv'\n",
    "\nDuring handling of the above exception, another exception occurred:\n\n",
    "Traceback (most recent call last):\n",
    "  File \"/Users/dustin/anaconda3/envs/RAISE/lib/python3.6/site-packages/sacred/config/captured_function.py\", line 42, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"../../train.py\", line 142, in train\n    env = make_env()\n",
    "  File \"/Users/dustin/anaconda3/envs/RAISE/lib/python3.6/site-packages/sacred/config/captured_function.py\", line 42, in captured_function\n    result = wrapped(*args, **kwargs)\n",
    "  File \"../../train.py\", line 114, in make_env\n    fourier_basis_size=10,\n",
    "  File \"/Users/dustin/Desktop/Clubs/RAISE/tf2multiagentrl/tf2marl/multiagent/SG_environment.py\", line 88, in __init__\n    self.prices = self._get_prices()\n",
    "  File \"/Users/dustin/Desktop/Clubs/RAISE/tf2multiagentrl/tf2marl/multiagent/SG_environment.py\", line 264, in _get_prices\n    price = price_signal(self.one_day, type_of_DR=type_of_DR)\n",
    "  File \"/Users/dustin/Desktop/Clubs/RAISE/tf2multiagentrl/tf2marl/multiagent/utils.py\", line 36, in price_signal\n    df = pd.read_csv(csv_path_3)\n",
    "  File \"/Users/dustin/anaconda3/envs/RAISE/lib/python3.6/site-packages/pandas/io/parsers.py\", line 688, in read_csv\n    return _read(filepath_or_buffer, kwds)\n",
    "  File \"/Users/dustin/anaconda3/envs/RAISE/lib/python3.6/site-packages/pandas/io/parsers.py\", line 454, in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\n",
    "  File \"/Users/dustin/anaconda3/envs/RAISE/lib/python3.6/site-packages/pandas/io/parsers.py\", line 948, in __init__\n    self._make_engine(self.engine)\n",
    "  File \"/Users/dustin/anaconda3/envs/RAISE/lib/python3.6/site-packages/pandas/io/parsers.py\", line 1180, in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n",
    "  File \"/Users/dustin/anaconda3/envs/RAISE/lib/python3.6/site-packages/pandas/io/parsers.py\", line 2010, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n",
    "  File \"pandas/_libs/parsers.pyx\", line 382, in pandas._libs.parsers.TextReader.__cinit__\n",
    "  File \"pandas/_libs/parsers.pyx\", line 674, in pandas._libs.parsers.TextReader._setup_parser_source\n",
    "FileNotFoundError: [Errno 2] No such file or directory: '/Users/dustin/Desktop/Clubs/RAISE/tf2multiagentrl/tf2marl/multiagent/../../transactive_control/gym-socialgame/gym_socialgame/envs/building_data.csv'\n"
  ],
  "heartbeat": "2021-04-07T08:23:50.370284",
  "host": {
    "ENV": {},
    "cpu": "Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz",
    "hostname": "Dustins-MBP",
    "os": [
      "Darwin",
      "Darwin-18.7.0-x86_64-i386-64bit"
    ],
    "python_version": "3.6.9"
  },
  "meta": {
    "command": "train",
    "options": {
      "--beat-interval": null,
      "--capture": null,
      "--comment": null,
      "--debug": false,
      "--enforce_clean": false,
      "--file_storage": null,
      "--force": false,
      "--help": false,
      "--loglevel": null,
      "--mongo_db": null,
      "--name": null,
      "--pdb": false,
      "--print-config": false,
      "--priority": null,
      "--queue": false,
      "--s3": null,
      "--sql": null,
      "--tiny_db": null,
      "--unobserved": false,
      "COMMAND": null,
      "UPDATE": [],
      "help": false,
      "with": false
    }
  },
  "resources": [],
  "result": null,
  "start_time": "2021-04-07T08:23:50.346709",
  "status": "FAILED",
  "stop_time": "2021-04-07T08:23:50.372688"
}